export interface Spark {
  id: string;
  category: string;
  categoryIcon: string;
  title: string;
  description: string;
  budgetMin: number;
  budgetMax: number;
  timelineLabel: string;
  skills: string[];
  postedHoursAgo: number;
  matchCount: number;
  featured?: boolean;
}

export const SPARK_CATEGORIES = [
  { id: "all",      label: "All Sparks", icon: "auto_awesome"    },
  { id: "code",     label: "Code",       icon: "code"            },
  { id: "design",   label: "Design",     icon: "palette"         },
  { id: "copy",     label: "Copy",       icon: "edit_note"       },
  { id: "data",     label: "Data",       icon: "analytics"       },
  { id: "motion",   label: "Motion",     icon: "movie_filter"    },
  { id: "research", label: "Research",   icon: "travel_explore"  },
];

export const MOCK_SPARKS: Spark[] = [
  {
    id: "sp1",
    category: "code",
    categoryIcon: "code",
    title: "Fix a critical React re-render bug",
    description: "Our main dashboard re-renders on every keystroke and loses input focus. Need a React expert to profile and fix — quick win for the right dev.",
    budgetMin: 100, budgetMax: 250,
    timelineLabel: "24 hours",
    skills: ["React", "Performance", "Profiling"],
    postedHoursAgo: 2,
    matchCount: 3,
    featured: true,
  },
  {
    id: "sp2",
    category: "design",
    categoryIcon: "palette",
    title: "Design a product landing page hero in Figma",
    description: "B2B SaaS hero section — headline, subheadline, CTA, product illustration. Dark mode variant included. Source file hand-off required.",
    budgetMin: 200, budgetMax: 400,
    timelineLabel: "2 days",
    skills: ["Figma", "UI Design", "SaaS"],
    postedHoursAgo: 5,
    matchCount: 5,
    featured: true,
  },
  {
    id: "sp3",
    category: "copy",
    categoryIcon: "edit_note",
    title: "Write 5 SaaS onboarding email sequences",
    description: "Welcome → activation → day-7 → upgrade path → win-back. Brand voice: direct, warm, no corporate fluff. One revision included.",
    budgetMin: 150, budgetMax: 300,
    timelineLabel: "3 days",
    skills: ["Email Copywriting", "SaaS", "CRO"],
    postedHoursAgo: 8,
    matchCount: 4,
  },
  {
    id: "sp4",
    category: "data",
    categoryIcon: "analytics",
    title: "Set up GA4 + conversion tracking for our funnel",
    description: "We need event tracking on signup, upgrade, and referral flows. GTM setup, custom dimensions, and a Looker Studio summary dashboard.",
    budgetMin: 150, budgetMax: 300,
    timelineLabel: "2 days",
    skills: ["GA4", "GTM", "Looker Studio"],
    postedHoursAgo: 12,
    matchCount: 2,
  },
  {
    id: "sp5",
    category: "code",
    categoryIcon: "code",
    title: "Build a Python script to scrape + normalise competitor pricing",
    description: "Scrape 3 competitor pricing pages, output clean JSON with product name, price tier, and feature list. Needs to handle JS-rendered pages.",
    budgetMin: 100, budgetMax: 200,
    timelineLabel: "2 days",
    skills: ["Python", "Playwright", "Data Cleaning"],
    postedHoursAgo: 14,
    matchCount: 6,
  },
  {
    id: "sp6",
    category: "design",
    categoryIcon: "palette",
    title: "Create 10 branded social media post templates",
    description: "Figma or Canva. Brand colours: electric violet + white. LinkedIn and Instagram square formats. Editable text layers.",
    budgetMin: 120, budgetMax: 200,
    timelineLabel: "2 days",
    skills: ["Figma", "Canva", "Brand Design"],
    postedHoursAgo: 18,
    matchCount: 7,
  },
  {
    id: "sp7",
    category: "research",
    categoryIcon: "travel_explore",
    title: "Competitive analysis report — 5 direct SaaS competitors",
    description: "Pricing, positioning, core features, onboarding UX, and 3 things each does better than us. Delivered as a Notion doc + slide deck.",
    budgetMin: 150, budgetMax: 300,
    timelineLabel: "3 days",
    skills: ["Market Research", "Competitive Intel", "Strategy"],
    postedHoursAgo: 20,
    matchCount: 3,
  },
  {
    id: "sp8",
    category: "motion",
    categoryIcon: "movie_filter",
    title: "Animated logo reveal — 15-second intro",
    description: "After Effects or exported as Lottie JSON. Should feel premium and modern, not template-y. Two colour variants (light + dark).",
    budgetMin: 100, budgetMax: 200,
    timelineLabel: "2 days",
    skills: ["After Effects", "Lottie", "Motion Design"],
    postedHoursAgo: 24,
    matchCount: 4,
  },
  {
    id: "sp9",
    category: "copy",
    categoryIcon: "edit_note",
    title: "Write technical docs for our REST API (10 endpoints)",
    description: "Request/response examples, error codes, auth flow, rate limits. Follow our existing style guide. Markdown format, ready for Mintlify.",
    budgetMin: 150, budgetMax: 250,
    timelineLabel: "2 days",
    skills: ["Technical Writing", "API Docs", "Markdown"],
    postedHoursAgo: 30,
    matchCount: 2,
  },
  {
    id: "sp10",
    category: "design",
    categoryIcon: "palette",
    title: "Design a 10-slide seed-stage pitch deck",
    description: "Problem → solution → market size → traction → team → ask. Figma source file with editable text. Tailored to fintech vertical.",
    budgetMin: 300, budgetMax: 500,
    timelineLabel: "3 days",
    skills: ["Presentation Design", "Figma", "Storytelling"],
    postedHoursAgo: 36,
    matchCount: 5,
    featured: true,
  },
  {
    id: "sp11",
    category: "code",
    categoryIcon: "code",
    title: "Integrate Stripe billing into our Next.js app",
    description: "Checkout sessions, webhook handlers for subscription events (created, updated, cancelled), customer portal, and a /billing page.",
    budgetMin: 200, budgetMax: 400,
    timelineLabel: "2 days",
    skills: ["Stripe", "Next.js", "TypeScript"],
    postedHoursAgo: 40,
    matchCount: 4,
  },
  {
    id: "sp12",
    category: "research",
    categoryIcon: "travel_explore",
    title: "UX audit of 3 key user flows",
    description: "Onboarding, core feature use, and upgrade flow. Heuristic evaluation using Nielsen's 10 principles + Loom walkthrough recordings.",
    budgetMin: 200, budgetMax: 350,
    timelineLabel: "3 days",
    skills: ["UX Research", "Heuristic Evaluation", "Loom"],
    postedHoursAgo: 48,
    matchCount: 3,
  },
];
