-- HYRDE Demo Seed: fresh open tasks for live demo
-- Run this in Supabase SQL Editor after 0004_claims.sql

INSERT INTO tasks (id, title, brief, category, origin, status, agent_completion, amount_cents)
VALUES
  (gen_random_uuid(),
   'Build iOS punch list feature for field crews',
   'We need a native SwiftUI screen where construction foremen can create, assign, and close punch list items on-site. Must work offline, sync when back online. VIPER architecture preferred. Target: iOS 17+.',
   'Development',
   'human',
   'open',
   0,
   30000),

  (gen_random_uuid(),
   'Design RFI submission form (construction)',
   'Create a Figma prototype for a Request for Information flow used by subcontractors. Must include file attachment, urgency level, and reviewer assignment. Dark + light mode. Deliverable: Figma file + iOS design spec.',
   'Design',
   'human',
   'agent_attempted',
   72,
   20000),

  (gen_random_uuid(),
   'Write technical docs for REST API endpoints',
   'Document 15 API endpoints for a project management platform. Must include curl examples, JSON schemas, error codes, and authentication flow. Output: Markdown files pushed to GitHub.',
   'Writing',
   'human',
   'open',
   0,
   8500),

  (gen_random_uuid(),
   'Data pipeline for construction cost tracking',
   'Build a Python ETL pipeline that ingests CSV exports from QuickBooks, normalizes cost codes, and loads into a Postgres table. Must run on AWS Lambda. Deliverable: Lambda function + schema migration.',
   'Engineering',
   'human',
   'agent_attempted',
   55,
   45000),

  (gen_random_uuid(),
   'iOS push notifications for task updates',
   'Implement APNs push notification support in an existing SwiftUI app. Must handle foreground/background delivery, notification actions, and deep-link routing. Must use UserNotifications framework.',
   'Development',
   'human',
   'open',
   0,
   18000),

  (gen_random_uuid(),
   'Social media content for product launch',
   'Create 30-day content calendar for LinkedIn, Instagram, and Twitter for a B2B SaaS launch. Must include 10 carousel posts, 20 short-form posts, and 5 short video scripts. AI-friendly briefs welcome.',
   'Marketing',
   'human',
   'open',
   0,
   12000),

  (gen_random_uuid(),
   'Audit and fix Core Data migration path',
   'Our iOS app has a broken Core Data migration from v3 to v4. Users are losing data on upgrade. Need someone to write lightweight migration mappings and add unit tests. Stack: Swift + Core Data + XCTest.',
   'Development',
   'human',
   'agent_attempted',
   40,
   22000),

  (gen_random_uuid(),
   'Finance dashboard for contractor invoices',
   'Build a SwiftUI screen showing invoice list, paid/unpaid totals, and a weekly earnings chart using Swift Charts framework. Pull data from a REST API. Must match existing dark-mode design system.',
   'Development',
   'human',
   'open',
   0,
   25000),

  (gen_random_uuid(),
   'QA testing for Android construction app',
   'Manual + automated QA for a construction site inspection app before App Store submission. Write XCUITest cases for critical flows: login, inspection creation, photo upload, offline sync.',
   'QA',
   'human',
   'open',
   0,
   9000),

  (gen_random_uuid(),
   'Redesign onboarding flow — 5 screens',
   'Our pilot onboarding has 40% drop-off at screen 3. Redesign the 5-screen flow with better copy, progress indicators, and value-prop framing. Deliverable: Figma prototype + A/B copy variants.',
   'Design',
   'human',
   'agent_attempted',
   88,
   16000);
